[build]
  publish = "public"
  functions = "netlify/functions"

# Optional: local dev proxy (netlify dev)
[[redirects]]
  from = "/submit-payment"
  to = "/.netlify/functions/submit-payment"
  status = 200

[[redirects]]
  from = "/upi-confirm"
  to = "/.netlify/functions/upi-confirm"
  status = 200

[[redirects]]
  from = "/create-order"
  to = "/.netlify/functions/create-order"
  status = 200

[[redirects]]
  from = "/razorpay-webhook"
  to = "/.netlify/functions/razorpay-webhook"
  status = 200

[[redirects]]
  from = "/verify-payment"
  to = "/.netlify/functions/verify-payment"
  status = 200


